from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIntValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.cgchartLable = QtWidgets.QLabel(self.centralwidget)
        self.cgchartLable.setGeometry(QtCore.QRect(10, 0, 600, 800))
        self.canvas = QPixmap("cgchart.png")
        self.cgchartLable.setPixmap(self.canvas)

        self.cgchartLable.setScaledContents(True)
        self.cgchartLable.setObjectName("cgchartLable")


        self.AcftIDComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.AcftIDComboBox.setGeometry(QtCore.QRect(620, 60, 113, 31))
        self.AcftIDComboBox.setPlaceholderText("Бортовой №")
        self.AcftIDComboBox.setObjectName("AcftIDComboBox")

        self.AddAcftIDPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddAcftIDPushButton.setGeometry(QtCore.QRect(740, 60, 113, 31))
        self.AddAcftIDPushButton.setObjectName("AddAcftIDPushButton")


        self.FlightNoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FlightNoLineEdit.setGeometry(QtCore.QRect(760, 20, 91, 31))
        self.FlightNoLineEdit.setObjectName("FlightNoLineEdit")


        self.DepartureDateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.DepartureDateTimeEdit.setGeometry(QtCore.QRect(620, 20, 130, 31))
        self.DepartureDateTimeEdit.setCalendarPopup(True)
        self.DepartureDateTimeEdit.setObjectName("DepartureDateTimeEdit")
        self.DepartureDateTimeEdit.setDate(QtCore.QDate.currentDate())

        self.DepAptLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.DepAptLineEdit.setGeometry(QtCore.QRect(620, 100, 113, 31))
        self.DepAptLineEdit.setObjectName("DepAptLineEdit")
        self.ArrAtpLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ArrAtpLineEdit.setGeometry(QtCore.QRect(740, 100, 113, 31))
        self.ArrAtpLineEdit.setObjectName("ArrAtpLineEdit")

        self.CrewComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.CrewComboBox.setGeometry(QtCore.QRect(620, 140, 113, 31))
        self.CrewComboBox.setObjectName("CrewComboBox")

        CargoValidator = QIntValidator(0, 6300)
        self.CargoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CargoLineEdit.setValidator(CargoValidator)
        self.CargoLineEdit.setGeometry(QtCore.QRect(740, 140, 113, 31))
        self.CargoLineEdit.setObjectName("CargoLineEdit")

        TO_Fuel_Validator = QIntValidator(0, 4900)
        self.TOFuelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TOFuelLineEdit.setValidator(TO_Fuel_Validator)
        self.TOFuelLineEdit.setGeometry(QtCore.QRect(620, 180, 113, 31))
        self.TOFuelLineEdit.setObjectName("TOFuelLineEdit")

        Trip_Fuel_Validator = QIntValidator()
        self.TripFuelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TripFuelLineEdit.setValidator(Trip_Fuel_Validator)
        self.TripFuelLineEdit.setGeometry(QtCore.QRect(740, 180, 113, 31))
        self.TripFuelLineEdit.setObjectName("TripFuelLineEdit")

        self.WeightCalcPB = QtWidgets.QPushButton(self.centralwidget)
        self.WeightCalcPB.setGeometry(QtCore.QRect(740, 310, 113, 31))
        self.WeightCalcPB.setObjectName("WeightCalcPB")

        self.weight = QtWidgets.QLabel(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(740, 350, 113, 150))
        self.weight.setAlignment(QtCore.Qt.AlignCenter)
        self.weight.setObjectName("weight")

        self.Del1pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del1pushButton.setGeometry(QtCore.QRect(620, 230, 30, 30))
        self.Del1pushButton.setObjectName("Del1pushButton")
        self.Add1pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add1pushButton.setGeometry(QtCore.QRect(700, 230, 30, 30))
        self.Add1pushButton.setObjectName("Add1pushButton")
        self.Pl1label = QtWidgets.QLabel(self.centralwidget)
        self.Pl1label.setGeometry(QtCore.QRect(660, 236, 31, 21))
        self.Pl1label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl1label.setObjectName("Pl1label")
        self.Del2pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del2pushButton.setGeometry(QtCore.QRect(620, 262, 30, 30))
        self.Del2pushButton.setObjectName("Del2pushButton")
        self.Pl2label = QtWidgets.QLabel(self.centralwidget)
        self.Pl2label.setGeometry(QtCore.QRect(660, 266, 31, 21))
        self.Pl2label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl2label.setObjectName("Pl2label")
        self.Add2pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add2pushButton.setGeometry(QtCore.QRect(700, 262, 30, 30))
        self.Add2pushButton.setObjectName("Add2pushButton")
        self.Del3pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del3pushButton.setGeometry(QtCore.QRect(620, 293, 30, 30))
        self.Del3pushButton.setObjectName("Del3pushButton")
        self.Del4pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del4pushButton.setGeometry(QtCore.QRect(620, 323, 30, 30))
        self.Del4pushButton.setObjectName("Del4pushButton")
        self.Del5pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del5pushButton.setGeometry(QtCore.QRect(620, 354, 30, 30))
        self.Del5pushButton.setObjectName("Del5pushButton")
        self.Del6pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del6pushButton.setGeometry(QtCore.QRect(620, 384, 30, 30))
        self.Del6pushButton.setObjectName("Del6pushButton")
        self.Del7pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del7pushButton.setGeometry(QtCore.QRect(620, 414, 30, 30))
        self.Del7pushButton.setObjectName("Del7pushButton")
        self.Del8pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del8pushButton.setGeometry(QtCore.QRect(620, 444, 30, 30))
        self.Del8pushButton.setObjectName("Del8pushButton")
        self.Del9pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del9pushButton.setGeometry(QtCore.QRect(620, 475, 30, 30))
        self.Del9pushButton.setObjectName("Del9pushButton")
        self.Del10pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del10pushButton.setGeometry(QtCore.QRect(620, 505, 30, 30))
        self.Del10pushButton.setObjectName("Del10pushButton")
        self.Del11pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del11pushButton.setGeometry(QtCore.QRect(620, 535, 30, 30))
        self.Del11pushButton.setObjectName("Del11pushButton")
        self.Del12pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del12pushButton.setGeometry(QtCore.QRect(620, 565, 30, 30))
        self.Del12pushButton.setObjectName("Del12pushButton")
        self.Del13pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Del13pushButton.setGeometry(QtCore.QRect(620, 596, 30, 30))
        self.Del13pushButton.setObjectName("Del13pushButton")
        self.Add3pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add3pushButton.setGeometry(QtCore.QRect(700, 293, 30, 30))
        self.Add3pushButton.setObjectName("Add3pushButton")
        self.Add4pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add4pushButton.setGeometry(QtCore.QRect(700, 323, 30, 30))
        self.Add4pushButton.setObjectName("Add4pushButton")
        self.Add5pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add5pushButton.setGeometry(QtCore.QRect(700, 354, 30, 30))
        self.Add5pushButton.setObjectName("Add5pushButton")
        self.Add6pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add6pushButton.setGeometry(QtCore.QRect(700, 384, 30, 30))
        self.Add6pushButton.setObjectName("Add6pushButton")
        self.Add7pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add7pushButton.setGeometry(QtCore.QRect(700, 414, 30, 30))
        self.Add7pushButton.setObjectName("Add7pushButton")
        self.Add8pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add8pushButton.setGeometry(QtCore.QRect(700, 444, 30, 30))
        self.Add8pushButton.setObjectName("Add8pushButton")
        self.Add9pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add9pushButton.setGeometry(QtCore.QRect(700, 475, 30, 30))
        self.Add9pushButton.setObjectName("Add9pushButton")
        self.Add10pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add10pushButton.setGeometry(QtCore.QRect(700, 505, 30, 30))
        self.Add10pushButton.setObjectName("Add10pushButton")
        self.Add11pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add11pushButton.setGeometry(QtCore.QRect(700, 535, 30, 30))
        self.Add11pushButton.setObjectName("Add11pushButton")
        self.Add12pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add12pushButton.setGeometry(QtCore.QRect(700, 565, 30, 30))
        self.Add12pushButton.setObjectName("Add12pushButton")
        self.Add13pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add13pushButton.setGeometry(QtCore.QRect(700, 596, 30, 30))
        self.Add13pushButton.setObjectName("Add13pushButton")
        self.Pl3label = QtWidgets.QLabel(self.centralwidget)
        self.Pl3label.setGeometry(QtCore.QRect(660, 299, 31, 21))
        self.Pl3label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl3label.setObjectName("Pl3label")
        self.Pl4label = QtWidgets.QLabel(self.centralwidget)
        self.Pl4label.setGeometry(QtCore.QRect(660, 330, 31, 21))
        self.Pl4label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl4label.setObjectName("Pl4label")
        self.Pl5label = QtWidgets.QLabel(self.centralwidget)
        self.Pl5label.setGeometry(QtCore.QRect(660, 360, 31, 21))
        self.Pl5label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl5label.setObjectName("Pl5label")
        self.Pl6label = QtWidgets.QLabel(self.centralwidget)
        self.Pl6label.setGeometry(QtCore.QRect(660, 390, 31, 21))
        self.Pl6label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl6label.setObjectName("Pl6label")
        self.Pl7label = QtWidgets.QLabel(self.centralwidget)
        self.Pl7label.setGeometry(QtCore.QRect(660, 420, 31, 21))
        self.Pl7label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl7label.setObjectName("Pl7label")
        self.Pl8label = QtWidgets.QLabel(self.centralwidget)
        self.Pl8label.setGeometry(QtCore.QRect(660, 450, 31, 21))
        self.Pl8label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl8label.setObjectName("Pl8label")
        self.Pl9label = QtWidgets.QLabel(self.centralwidget)
        self.Pl9label.setGeometry(QtCore.QRect(660, 480, 31, 21))
        self.Pl9label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl9label.setObjectName("Pl9label")
        self.Pl10label = QtWidgets.QLabel(self.centralwidget)
        self.Pl10label.setGeometry(QtCore.QRect(660, 510, 31, 21))
        self.Pl10label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl10label.setObjectName("Pl10label")
        self.Pl11label = QtWidgets.QLabel(self.centralwidget)
        self.Pl11label.setGeometry(QtCore.QRect(660, 540, 31, 21))
        self.Pl11label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl11label.setObjectName("Pl11label")
        self.Pl12label = QtWidgets.QLabel(self.centralwidget)
        self.Pl12label.setGeometry(QtCore.QRect(660, 570, 31, 21))
        self.Pl12label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl12label.setObjectName("Pl12label")
        self.Pl13label = QtWidgets.QLabel(self.centralwidget)
        self.Pl13label.setGeometry(QtCore.QRect(660, 600, 31, 21))
        self.Pl13label.setAlignment(QtCore.Qt.AlignCenter)
        self.Pl13label.setObjectName("Pl13label")
        self.PrintPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrintPushButton.setGeometry(QtCore.QRect(620, 640, 85, 33))
        self.PrintPushButton.setObjectName("PrintPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FlightNoLineEdit.setPlaceholderText(_translate("MainWindow", "№ Рейса"))
        self.AddAcftIDPushButton.setText(_translate("MainWindow", "Новый самолет"))
        self.DepartureDateTimeEdit.setToolTip(_translate("MainWindow", "Дата и время вылета"))
        self.DepAptLineEdit.setPlaceholderText(_translate("MainWindow", "Откуда"))
        self.ArrAtpLineEdit.setPlaceholderText(_translate("MainWindow", "Куда"))
        self.CrewComboBox.setToolTip(_translate("MainWindow", "Экипаж"))
        self.CrewComboBox.setPlaceholderText(_translate("MainWindow", "Экипаж"))
        self.CargoLineEdit.setPlaceholderText(_translate("MainWindow", "Ком. Загрузка"))
        self.TOFuelLineEdit.setPlaceholderText(_translate("MainWindow", "Q на взлете"))
        self.TripFuelLineEdit.setPlaceholderText(_translate("MainWindow", "Q расходуемое"))
        self.WeightCalcPB.setText(_translate("MainWindow", "Рассчитать"))

        #self.weight.setText(_translate("MainWindow", "G"))

        self.Del1pushButton.setText(_translate("MainWindow", "-"))
        self.Add1pushButton.setText(_translate("MainWindow", "+"))
        self.Pl1label.setText(_translate("MainWindow", "0000"))
        self.Del2pushButton.setText(_translate("MainWindow", "-"))
        self.Pl2label.setText(_translate("MainWindow", "0000"))
        self.Add2pushButton.setText(_translate("MainWindow", "+"))
        self.Del3pushButton.setText(_translate("MainWindow", "-"))
        self.Del4pushButton.setText(_translate("MainWindow", "-"))
        self.Del5pushButton.setText(_translate("MainWindow", "-"))
        self.Del6pushButton.setText(_translate("MainWindow", "-"))
        self.Del7pushButton.setText(_translate("MainWindow", "-"))
        self.Del8pushButton.setText(_translate("MainWindow", "-"))
        self.Del9pushButton.setText(_translate("MainWindow", "-"))
        self.Del10pushButton.setText(_translate("MainWindow", "-"))
        self.Del11pushButton.setText(_translate("MainWindow", "-"))
        self.Del12pushButton.setText(_translate("MainWindow", "-"))
        self.Del13pushButton.setText(_translate("MainWindow", "-"))
        self.Add3pushButton.setText(_translate("MainWindow", "+"))
        self.Add4pushButton.setText(_translate("MainWindow", "+"))
        self.Add5pushButton.setText(_translate("MainWindow", "+"))
        self.Add6pushButton.setText(_translate("MainWindow", "+"))
        self.Add7pushButton.setText(_translate("MainWindow", "+"))
        self.Add8pushButton.setText(_translate("MainWindow", "+"))
        self.Add9pushButton.setText(_translate("MainWindow", "+"))
        self.Add10pushButton.setText(_translate("MainWindow", "+"))
        self.Add11pushButton.setText(_translate("MainWindow", "+"))
        self.Add12pushButton.setText(_translate("MainWindow", "+"))
        self.Add13pushButton.setText(_translate("MainWindow", "+"))
        self.Pl3label.setText(_translate("MainWindow", "0000"))
        self.Pl4label.setText(_translate("MainWindow", "0000"))
        self.Pl5label.setText(_translate("MainWindow", "0000"))
        self.Pl6label.setText(_translate("MainWindow", "0000"))
        self.Pl7label.setText(_translate("MainWindow", "0000"))
        self.Pl8label.setText(_translate("MainWindow", "0000"))
        self.Pl9label.setText(_translate("MainWindow", "0000"))
        self.Pl10label.setText(_translate("MainWindow", "0000"))
        self.Pl11label.setText(_translate("MainWindow", "0000"))
        self.Pl12label.setText(_translate("MainWindow", "0000"))
        self.Pl13label.setText(_translate("MainWindow", "0000"))
        self.PrintPushButton.setText(_translate("MainWindow", "Печать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
